### ISSUE TITLE
Claim-Order dependent staking rewards

### ISSUE THREAD

**Issue by 0x-r4bbit** [logos-co/staking#11]
Original author: @mart1n-xyz 

The current Solidity implementation gives more rewards to earlier claimers. **This will results in shortage of funds!** 

Suppose there are 2 identical stakers only (call them Alice and Bob). Both of them are going to claim rewards for the same past epoch. Let’s ignore the fact that they likely claim multiple epochs and focus on the oldest/first one they claim. Suppose that there is 1000 SNT to be rewarded (split between the two stakers) in this epoch. A correct outcome is a 500/500 split between them. However, as we’ll see this is not the outcome of the current contract implementation. 

Suppose Alice calls `processAccount` first. The function mints her multiplier points for this epoch and to determine her share of pending SNT rewards, the function computes:

```solidity
uint256 userShare = (account.balance + account.multiplier)/ iEpoch.totalSupply;
```

i.e. the sum of Alice’s multiplier points and SNT stake, divided by the sum of all staked SNT and all multiplier points (multiplierSupply + stakeSupply).  

The issue lies in the fact that Bob’s multiplier points for this epoch have not been yet minted and, therefore, are not reflected in the `iEpoch.totalSupply` . Thus, the `totalSupply` equals

$$2(STAKE_{SNT}+STAKE_{MP})+r_{MP}*STAKE_{MP},$$

 where the STAKE variables represent staked SNT and MPs (identical fro both users), and  $r_{MP}*STAKE_{MP}$ is the multiplier points Alice earned in this epoch. It follows that her userShare , the portion of pending SNT rewards she can claim, is

$$\frac{STAKE_{SNT}+STAKE_{MP}+r_{MP}*STAKE_{MP}}{2(STAKE_{SNT}+STAKE_{MP})+r_{MP}*STAKE_{MP}}>\frac{1}{2}.$$

Hence, her payoff will be larger than 500 SNT. 

For the sake of completeness, let’s review the case of Bob. Once Bob claims his rewards, he will mint his multiplier points and these will be reflected in totals. His `userShare` will be computed as

$$\frac{STAKE_{SNT}+STAKE_{MP}+r_{MP}*STAKE_{MP}}{2(STAKE_{SNT}+STAKE_{MP}+r_{MP}*STAKE_{MP})}=\frac{1}{2}.$$

He is eligible for his correct share. Nevertheless, he won’t be able to make the claim since we know that the contract already paid out more than 500 SNT and, thus, 500 SNT is not available for Bob’s claim as the contract is running at a loss. 

### Possible solution

The core of the issue lies in the fact that we do not know the total of multiplier points in a certain epoch until all stakers process their accounts. Even if we were to decouple the computation of MPs and share of pending rewards (such that the MP total is known before rewards are paid out), we must reflect the fact that not all stakers will process their accounts in a reasonable timeframe after the epoch (e.g. lost seed case). These findings indicate that any computation of totals based on individual `processAccount` calls will suffer from similar flaws and will be inaccurate.

Therefore, the totals for the epoch have to be derived based on stored aggregates of the previous epoch. We are, actually, well positioned to make such an approximation as the MP APY is fixed. Therefore, we can take the total amount of SNT stake and derive the total MPs that are to be minted (stakers receive 100% MP APY on their SNT stake) in this epoch. That can be used to compute `iEpoch.totalSupply` and this result will be the same for all stakers calling `processAccount`. 

This way, we would be able to derive a plausible result. However, there will still be inaccuracy due to limits on multiplier points. When we assume that a certain number of MPs will be minted in the epoch, we ignore the fact that some users collecting this mint might be hitting their multiplier limit. Since we are operating with aggregates, we are not able to account for individual specifics of staker accounts and we cannot estimate what fraction of MPs will not be minted due to these individual constraints. We can only check that the ratio of MPs to SNT stake is not over the limit on aggregate (which is not likely to provide much benefit). 

Therefore, we end up in a situation where we overestimate the `totalSupply`. That means stakers will receive slightly smaller share of rewards and there will be some rewards left in the smart contract. It is debatable if this approach is acceptable. Arguably, the leftover SNT would be rather small and leaving it in the contract is equivalent to burning it (there are protocols who burn a share of collected fees and redistribute the rest to stakers).

**Comment by 0x-r4bbit** [comment]
@mart1n-xyz will this be addressed by #48 ?

**Comment by mart1n-xyz** [comment]
Yes.

**Comment by 0x-r4bbit** [comment]
Thank you! Then I'll close this one
