### ISSUE TITLE
Fix wrong accounting in `stake()` when `mintBonusMP`

### ISSUE THREAD

**Issue by 0x-r4bbit** [logos-co/staking#111]
When staking, we currently 

1) first increase the `account.balance` (https://github.com/logos-co/staking/blob/develop/contracts/StakeManager.sol#L208)
2) *then* we mint bonus mp (https://github.com/logos-co/staking/blob/develop/contracts/StakeManager.sol#L208) with `account` and `stakeAmount`

The result is that we're accounting for `stakeAmount` twice, once as part of `account.balance` and once via `stakeAmount`.
This needs to be fixed.

Also, provide a test that proofs the fix

**Comment by 3esmit** [comment]
Fixed by https://github.com/logos-co/staking/pull/115
