### ISSUE TITLE
When stake unlocked, increasing stake and locking using stake() mints bonus MPs only for this increment

### ISSUE THREAD

**Issue by 0x-r4bbit** [logos-co/staking#13]
Original author: @mart1n-xyz 

Suppose a user has an existing stake that has not been locked and wants to increase his stake and lock it all. There are 2 ways of achieving this:

- Call `stake()` with no lock and call `lock()` to lock the stake.
- Call `stake()` with lock.

The problem occurs in the latter case where bonus MPs for the lock are minted only for the increment of the stake that is being deposited.

### Possible solution

An easy fix is to decouple locking from the staking function and preserve the functionality only within `lock()`. Or disable adding stake after initial deposit as outlined in Status Staking Summary.

Alternatively, `mintIntialMultiplier()` can be called within `stake()` in a way that it is called to mint the initial unconditional bonus (100% of stake in MP) on the deposited account and then called again to mint the lock bonus on the entire account balance (or just call `lock()`).

**Comment by 0x-r4bbit** [comment]
I think this goes somewhat hand in had with #17 
If we say we don't allow for adding stake to existing vaults but always create a new vault, then this issue will no longer be a problem, or am I missing something here?

**Comment by mart1n-xyz** [comment]
> If we say we don't allow for adding stake to existing vaults but always create a new vault, then this issue will no longer be a problem, or am I missing something here?

Yes, that is correct.
