### ISSUE TITLE
Complete migration strategy functionality

### ISSUE THREAD

**Issue by 3esmit** [logos-co/staking#21]
_Edited by @0x-r4bbit_:

Adding some context here: 

There were a bunch of missing pieces and bugs in the migration strategy.
Some of them have been addressed in #47

**Comment by 0x-r4bbit** [comment]
@3esmit I've added some context to this issue.

I'm unsure however what's the current state of migration. If I remember correctly, there were still some things missing.
Can you please add a comment here with what's left to be done for migration only?

**Comment by 3esmit** [comment]
Fixed on #59
