### ISSUE TITLE
Fix Floating-Point Number Calculations in Contract

### ISSUE THREAD

**Issue by mart1n-xyz** [logos-co/staking#24]
There are potential issues with how our contract handles calculations that require floating-point precision. Solidity doesn't natively support floating-point numbers, and our current approach may result in errors or lost precision.

Consider introducing fixed-point arithmetic by scaling numbers to maintain precision. Or utilize libraries or tools that can help in managing and maintaining precision in mathematical operations.

**Comment by 3esmit** [comment]
Sorry for creating a duplicate of this.

**Comment by 0x-r4bbit** [comment]
Let's close this one in favour of #64 as #64 is more elaborate and has some research notes attached to it.
