### ISSUE TITLE
EPOCH_SIZE used in processAccount

### ISSUE THREAD

**Issue by mart1n-xyz** [logos-co/staking#31]
However, epochs may have various sizes (EPOCH_SIZE is only the min size of the epoch). In this case, a user is then only earning rewards on the standard size of the epoch and then none for the "overtime".

**Comment by 0x-r4bbit** [comment]
@mart1n-xyz Do you think this issue is still relevant?

AFAIK epoch size is used as interval and `processAccount` can/will be called multiple times to process all epochs up to "now".

If you think this issue is still actionable, please elaborate and we can keep it open.

**Comment by mart1n-xyz** [comment]
Fair point, feel free to close
