### ISSUE TITLE
Make MPs usable for Snapshot governance 

### ISSUE THREAD

**Issue by mart1n-xyz** [logos-co/staking#33]
Currently staked SNT is an ERC20 token (or not?) - however, I am not sure it is implemented correctly as the functions changing balances do not utilize the ERC20 functions.

However, a more necessary feature is to make MPs work with governance solutions (Snapshot rankings is the short-term target). Therefore, we need to provide public read functions to access balances - whether this is using ERC20 or not depends on the additional complexity. 

We might consider using ERC20Votes.sol for futureproofing if proper decentralized governance were a long-term target. However, in such a case the contract can be. updated.

**Comment by 0x-r4bbit** [comment]
I'm flagging this with low priority for as we need to discuss what governance exactly will entail but for now I think we should focus on getting the staking functionality right first.

**Comment by mart1n-xyz** [comment]
The governance is a separate process that currently uses Snapshot for voting on NIPs posted on discourse. Not sure how this will evolve, however, having at least ERC20 read functionality for MP balance would suffice for now.

**Comment by 3esmit** [comment]
It would be possible to include balanceOf functions in the StakeManager, which would return whatever we want. transfer would not be implemented.

**Comment by 3esmit** [comment]
Added label of feature, as it would be a feature, and refactor, as it would probably need refactor (in case we need to inherit Votes.sol from OpenZeppelin)

**Comment by mart1n-xyz** [comment]
We'll likely need Snapshot compatibility in the foreseeable future. Votes.sol would be futureproofing that can, however, be addressed by migration to a new contract if necessary.

**Comment by 0x-r4bbit** [comment]
Unassigning @3esmit for now as this is not actually being worked on atm.

**Comment by 0x-r4bbit** [comment]
MP will not be part of governance. If at all, it's going to be XP * SNT.
This stuff is not actually something we're working on atm moment and it seems unclear if we will be going down that path.
Closing this issue for now and will revisit once this is more relevant.
