### ISSUE TITLE
Build a rewardCollector contract

### ISSUE THREAD

**Issue by mart1n-xyz** [logos-co/staking#34]
rewardCollector is a contract that collects rewards from all user's vaults (these point to its address). It has the following functionality:

- restake in a new vault with optional lock = deploy a new vault, stake and lock if desirable
- restake in an existing non-locked vault = add stake to existing vault
- withdraw rewards = apply cooldown period and send rewards to user's address (might be a 2-step procedure due to cooldown)

Only one withdrawal can be "waiting at a time" for simplicity, for a start.

**Comment by 0x-r4bbit** [comment]
I'm going to close this, as per latest discussions, we're not able to pay out any rewards in SNT, so reward collector vault is no longer needed.
