### ISSUE TITLE
Add tests to improve coverage of existing functionality

### ISSUE THREAD

**Issue by 3esmit** [logos-co/staking#68]
Tests to be written:
 - [ ] tests for process epoch:
     - [x] should update pending rewards
     - [x] should update total supply
     - [ ] should update total supply multiplier points
     - [x] should increase epoch
 - [ ] tests for process account:
     - [x] should update user multiplier points
     - [ ] should update user epoch
     - [ ] should pay user proportional rewards
 - [ ] tests for stake
     - [ ] should update user lockup time
     - [ ] should mint bonus multiplier points
     - [ ] should update bonus multiplier points (restake)
     - [ ] should update total supply multiplier points
     - [ ] should update total supply balance
     - [ ] should update total supply
 - [ ] tests for lock
     - [ ] should update user lockup time
     - [ ] should update bonus multiplier points
     - [ ] should update total supply multiplier points
 - [ ] tests for unstake
     - [ ] should burn multiplier points
     - [ ] should update total supply multiplier points
     - [ ] should update total supply balance
     - [ ] should update total supply

**Comment by 0x-r4bbit** [comment]
@3esmit FYI: I've updated the issue description so it's a bit more actionable.
